global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'teastore-services'
    static_configs:
      - targets: 
        - 'telegraf:9273'
        - 'registry:1111'
        - 'persistence:2222'
        - 'auth:3333'
        - 'webui:8080'
